### ISSUE TITLE
For some reason is not compiling

### ISSUE THREAD

**Issue by gabrielbuzziv** [matfish2/vue-pagination-2#3]
- Vue.js version: **2.0.1**
- consumed using: **webpack**
- FULL error message (including stack trace):

```
{ [Error: ./~/vue-pagination-2/src/template.jsx
Module build failed: SyntaxError: Unexpected token (8:8)

   6 |   this.pages.map(function(page) {
   7 |       items.push(
>  8 |         <li class="VuePagination__pagination-item"
     |         ^
   9 |         class={this.activeClass(page)}>
  10 |         <a href="javascript:void(0);"
  11 |         on-click={this.setPage.bind(this, page)}>{page}</a>

BabelLoaderError: SyntaxError: Unexpected token (8:8)

   6 |   this.pages.map(function(page) {
   7 |       items.push(
>  8 |         <li class="VuePagination__pagination-item"
     |         ^
   9 |         class={this.activeClass(page)}>
  10 |         <a href="javascript:void(0);"
  11 |         on-click={this.setPage.bind(this, page)}>{page}</a>

    at transpile (/var/www/vuejs/node_modules/babel-loader/index.js:52:13)
    at Object.module.exports (/var/www/vuejs/node_modules/babel-loader/index.js:131:12)
 @ ./~/vue-pagination-2/src/Pagination.js 1:15-40
 @ ./~/vue-pagination-2/index.js
 @ ./resources/assets/js/main.js]
  message: './~/vue-pagination-2/src/template.jsx\nModule build failed: SyntaxError: Unexpected token (8:8)\n\n\u001b[0m \u001b[90m  6 | \u001b[39m  \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mpages\u001b[33m.\u001b[39mmap(\u001b[36mfunction\u001b[39m(page) {\n \u001b[90m  7 | \u001b[39m      items\u001b[33m.\u001b[39mpush(\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m  8 | \u001b[39m        \u001b[33m<\u001b[39m\u001b[33mli\u001b[39m \u001b[36mclass\u001b[39m\u001b[33m=\u001b[39m\u001b[32m"VuePagination__pagination-item"\u001b[39m\n \u001b[90m    | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m  9 | \u001b[39m        \u001b[36mclass\u001b[39m\u001b[33m=\u001b[39m{\u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mactiveClass(page)}\u001b[33m>\u001b[39m\n \u001b[90m 10 | \u001b[39m        \u001b[33m<\u001b[39m\u001b[33ma\u001b[39m href\u001b[33m=\u001b[39m\u001b[32m"javascript:void(0);"\u001b[39m\n \u001b[90m 11 | \u001b[39m        on\u001b[33m-\u001b[39mclick\u001b[33m=\u001b[39m{\u001b[36mthis\u001b[39m\u001b[33m.\u001b[39msetPage\u001b[33m.\u001b[39mbind(\u001b[36mthis\u001b[39m\u001b[33m,\u001b[39m page)}\u001b[33m>\u001b[39m{page}\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33ma\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\nBabelLoaderError: SyntaxError: Unexpected token (8:8)\n\n\u001b[0m \u001b[90m  6 | \u001b[39m  \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mpages\u001b[33m.\u001b[39mmap(\u001b[36mfunction\u001b[39m(page) {\n \u001b[90m  7 | \u001b[39m      items\u001b[33m.\u001b[39mpush(\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m  8 | \u001b[39m        \u001b[33m<\u001b[39m\u001b[33mli\u001b[39m \u001b[36mclass\u001b[39m\u001b[33m=\u001b[39m\u001b[32m"VuePagination__pagination-item"\u001b[39m\n \u001b[90m    | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m  9 | \u001b[39m        \u001b[36mclass\u001b[39m\u001b[33m=\u001b[39m{\u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mactiveClass(page)}\u001b[33m>\u001b[39m\n \u001b[90m 10 | \u001b[39m        \u001b[33m<\u001b[39m\u001b[33ma\u001b[39m href\u001b[33m=\u001b[39m\u001b[32m"javascript:void(0);"\u001b[39m\n \u001b[90m 11 | \u001b[39m        on\u001b[33m-\u001b[39mclick\u001b[33m=\u001b[39m{\u001b[36mthis\u001b[39m\u001b[33m.\u001b[39msetPage\u001b[33m.\u001b[39mbind(\u001b[36mthis\u001b[39m\u001b[33m,\u001b[39m page)}\u001b[33m>\u001b[39m{page}\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33ma\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\n    at transpile (/var/www/vuejs/node_modules/babel-loader/index.js:52:13)\n    at Object.module.exports (/var/www/vuejs/node_modules/babel-loader/index.js:131:12)\n @ ./~/vue-pagination-2/src/Pagination.js 1:15-40\n @ ./~/vue-pagination-2/index.js\n @ ./resources/assets/js/main.js',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

```

- relevant code:

**gulpfile.js**
```
elixir.webpack.mergeConfig({
    module: {
        loaders: [
            {
                test: /\.jsx$/,
                loader: 'babel'
            },
        ]
    }
})
```

- steps for reproducing the issue:

**Just followed the https://www.npmjs.com/package/vue-pagination-2 tutorial and tried to compile.**

**Comment by matfish2** [comment]
JSX transformer is clearly not working.
Did you follow the [installation instructions](https://github.com/vuejs/babel-plugin-transform-vue-jsx)? You need to register the plugin in your `.babelrc` file

**Comment by gabrielbuzziv** [comment]
Ok i didn't. Missed that part, thanks
